# Series - CP Chapter 2

## Question 1

a.  **(5 marks)** Prove that $$\sum_{r = 1}^{n}{\frac{3}{r(r + 1)} = \frac{an}{n + 1},\ n} \in \mathbb{Z}$$ where $a$ is a constant to be found.

b.  **(1 mark)** Find the value of $\sum_{r = 1}^{50}{\frac{3}{r(r + 1)}}$, giving your answer as an exact fraction.

c.  **(4 marks)** Find an expression in its simplest form for

$$\sum_{r = n}^{2n}{\frac{3}{r(r + 1)}}$$\

::: {.callout-tip title="Solution" collapse="true" icon="false"}
**a** We notice that $$\sum_{r=1}^{n}\frac{3}{r(r+1)}=3\sum_{r=1}^{n}\frac{1}{r(r+1)}$$ {#eq-1a} First, we need to express $\frac{1}{r(r+1)}$ in partial fractions. $$
\frac{1}{r(r+1)}=\frac{A}{r}+\frac{B}{r+1}$$ for some $A,B \in \mathbb{R}$.

By multiplying both sides by the common denominator $r(r+1)$, we have:

$$1=A(r+1)+Br $$ For $r=0$, we get $A=1$ and for $r=-1$, $B=-1$.

$$\therefore \qquad \frac{1}{r(r+1)}=\frac{1}{r}-\frac{1}{r+1} $$ So, from @eq-1a we have

$\sum_{r=1}^{n}\frac{3}{r(r+1)} \ \quad  = \quad 3\sum_{r=1}^{n} \left(\frac{1}{r}-\frac{1}{r+1}\right)$

\begin{alignat*}{3}
= \quad & 3 & \textcolor{magenta}{-} \qquad & \qquad  \textcolor{magenta}{\frac{3}{2}}  & \quad (r=1) \\
\textcolor{magenta}{+}  & \textcolor{magenta}{\frac{3}{2}}  &\textcolor{magenta}{-} \qquad& \qquad \textcolor{magenta}{ 1} & \quad (r=2) \\
\textcolor{magenta}{+} &\textcolor{magenta}{1} &\textcolor{magenta}{-} \qquad& \qquad  \textcolor{magenta}{\frac{3}{4}} & \quad (r=3) \\
&\textcolor{magenta}{\vdots} & & \quad & \\
\textcolor{magenta}{+}  & \textcolor{magenta}{\frac{3}{n-1}}  &\textcolor{magenta}{-} \qquad& \qquad  \textcolor{magenta}{\frac{3}{n}}  & \quad (r=n-1)\\
\textcolor{magenta}{+} & \textcolor{magenta}{\frac{3}{n}} & - \qquad & \qquad \frac{3}{n+1} & \quad (r=n)\\
= \quad & 3 - \frac{3}{n+1} & & \quad & 
\end{alignat*}

Thus, by simplifying $$\sum_{r=1}^{n}\frac{3}{r(r+1)}=\frac{3n}{n+1}, \quad \forall n \in \mathbb{Z} $$ {#eq-1b} Therefore, $a=3$.

**b** By substituting $n=50$ in @eq-1b $$\sum_{r=1}^{50}\frac{3}{r(r+1)}=\frac{3\times50}{50+1}=\frac{3 \times 50}{51}=\frac{3\times50}{3 \times17}=\frac{50}{17}$$

**c** We need to make the following observation about the range of values for r: $$\sum_{r=n}^{2n}\frac{3}{r(r+1)}=\sum_{r=1}^{2n}\frac{3}{r(r+1)}-\sum_{r=1}^{n-1}\frac{3}{r(r+1)}$$ By substituting the appropriate values in @eq-1b \begin{equation*}
\begin{split}
\sum_{r=n}^{2n}\frac{3}{r(r+1)} &= \frac{3 \times 2n}{2n+1}-\frac{3(n-1)}{n-1+1} \\
&= \frac{6n}{2n+1}-\frac{3n-3}{n} \\
&= \frac{6n^2-(3n-3)(2n+1)}{n(2n+1)}\\
&= \frac{6n^2-(6n^2-3n-3)}{n(2n+1)}\\
&=\frac{3n+3}{n(2n+1)}\\
&=\frac{3(n+1)}{n(2n+1)}
\end{split}
\end{equation*}
:::

## Question 2

a.  **(2 marks)** Simplify

$$r^2\ (r+1)^2-(r-1)^2\ r^2$$

b.  **(3 marks)** Use the method of differences to show that $\sum_{r=1}^{n}r^3=\frac{1}{4}n^2(n+1)^2$

::: {.callout-tip title="Solution" collapse="true" icon="false"}
**a** 
\begin{equation*}
\begin{split}
r^2 (r+1)^2-(r-1)^2 r^2 &= r^2 (r^2+2r+1)-(r^2-2r+1)r^2 \\
&= r^4+2r^3+r^2-(r^4-2r^3+r^2) \\
&= r^4+2r^3+r^2-r^4+2r^3-r^2 \\
&= 4r^3 \\
\end{split}
\end{equation*}


**b** From part a. we can deduce that $$r^3=\frac{1}{4}(r^2 (r+1)^2-(r-1)^2 r^2)$$ Therefore,

$\sum_{r=1}^{n}r^3  \quad = \quad \frac{1}{4}\sum_{r=1}^{n} \left(r^2 (r+1)^2-(r-1)^2 r^2\right)$ \begin{alignat*}{3}
= \quad & \textcolor{magenta}{1} &  -  & \qquad  0  & \quad (r=1) \\
\textcolor{magenta}{+}  & \textcolor{magenta}{\frac{2^2 \times 3^2}{4}}  &\textcolor{magenta}{-} &\qquad \textcolor{magenta}{1} & \quad (r=2) \\
\textcolor{magenta}{+} &\textcolor{magenta}{\frac{3^2 \times 4^2}{4}} &\textcolor{magenta}{-} &\qquad  \textcolor{magenta}{\frac{2^2 \times 3^2}{4}} & \quad (r=3) \\
&\textcolor{magenta}{\vdots} & & \quad & \\
\textcolor{magenta}{+}  & \textcolor{magenta}{\frac{(n-1)^2n^2}{4}}  &\textcolor{magenta}{-} & \qquad  \textcolor{magenta}{\frac{(n-2)^2(n-1)^2}{4}}  & \quad (r=n-1)\\
+ & \frac{n^2(n+1)^2}{4} \quad & -  & \qquad \textcolor{magenta}{\frac{(n-1)^2n^2}{4}} & \quad (r=n)\\
= \quad & \frac{n^2(n+1)^2}{4} & & \quad & 
\end{alignat*} Thus, $$\sum_{r=1}^{n}r^3=\frac{1}{4}n^2(n+1)^2$$
:::

## Question 3

a.  **(3 marks)** Express in partial fractions

$$\frac{2}{(r+2)(r+3)(r+4)}$$

b.  **(5 marks)** Show that $$\sum_{r=1}^{n}{\frac{2}{(r+2)(r+3)(r+4)}=\frac{n(n+b)}{c(n+3)(n+4)}}$$ where $b$ and $c$ are constants to be found.

::: {.callout-tip title="Solution" collapse="true" icon="false"}
**a**
$$\frac{2}{(r+2)(r+3)(r+4)} = \frac{A}{r+2}+\frac{B}{r+3}+\frac{C}{r+4}$$ for some $A, B, C \in \mathbb{R}$. By multiplying both sides by the common denominator $(r+2)(r+3)(r+4)$, we have $$2=A(r+3)(r+4)+B(r+2)(r+4)+C(r+2)(r+3)$$ For $r=-2$, we get $A=1$, for $r=-3$, $B=-2$ and for $r=-4$, $C=1$.

$$\therefore \qquad \frac{2}{(r+2)(r+3)(r+4)} = \frac{1}{r+2}-\frac{2}{r+3}+\frac{1}{r+4} $$ {#eq-2a}

**b** Using the result @eq-2a from part a

$\sum_{r=1}^{n}\frac{2}{(r+2)(r+3)(r+4)} = \sum_{r=1}^{n}\frac{1}{r+2}-\frac{2}{r+3}+\frac{1}{r+4}$ \begin{alignat*}{4}
= \quad & \qquad & \frac{1}{3}&  \qquad - &\qquad \frac{2}{4} & \qquad + & \qquad   \textcolor{magenta}{\frac{1}{5}}  & \quad (r=1) \\
& + & \quad  \frac{1}{4}& \qquad - & \qquad \textcolor{magenta}{\frac{2}{5}} & \qquad + & \qquad  \textcolor{blue}{\frac{1}{6}}  & \quad (r=2)\\
& + & \quad \textcolor{magenta}{\frac{1}{5}} & \qquad - & \qquad \textcolor{blue}{\frac{2}{6}} & \qquad + & \qquad  \textcolor{magenta}{\frac{1}{7}}  & \quad (r=3)\\
& + & \quad \textcolor{blue}{\frac{1}{6}} & \qquad - & \qquad \textcolor{magenta}{\frac{2}{7}} & \qquad + & \qquad  \textcolor{blue}{\frac{1}{8}}  & \quad (r=4)\\
&\vdots & & \quad & \\
& + & \quad \textcolor{magenta}{\frac{1}{n}}& \qquad - & \textcolor{blue}{\qquad \frac{2}{n+1}} & \qquad + & \qquad \textcolor{magenta}{\frac{1}{n+2}}  & \quad (r=n-2)\\
& + & \quad  \textcolor{blue}{\frac{1}{n+1}}& \qquad - & \textcolor{magenta}{\qquad \frac{2}{n+2}} & \qquad + & \qquad  \frac{1}{n+3}  & \quad (r=n-1)\\
& + & \quad  \textcolor{magenta}{\frac{1}{n+2}}& \qquad - & \qquad \frac{2}{n+3} & \qquad + & \qquad  \frac{1}{n+5}  & \quad (r=n) 
\end{alignat*}

Thus,

\begin{equation*}
\begin{split}
\sum_{r=1}^{n}\frac{2}{(r+2)(r+3)(r+4)}&= \frac{1}{2}-\frac{2}{4}+\frac{1}{4}+\frac{1}{n+3}-\frac{2}{n+4}+\frac{1}{n+4}\\
&=\frac{1}{12}-\frac{1}{n+3}+\frac{1}{n+4}\\
&= \frac{(n+3)(n+4)-12(n+4)+12(n+3)}{12(n+3)(n+4)}\\
&= \frac{n^2+7n+12-12n-48+12n+36}{12(n+3)(n+4)}\\
&= \frac{n^2+7n}{12(n+3)(n+4)}\\
&= \frac{n(n+7)}{12(n+3)(n+4)}
\end{split}
\end{equation*}

Thus, $b=7$ and $c=12$.
:::

## Question 4

a.  **(3 marks)** Use standard results to show that the first four terms of the series expansion of $e^{2-x}$ in ascending powers of $x$ can be expressed as

$$e^2\left(1-x+\frac{x^2}{2!}-\frac{x^3}{3!}\right)$$

b.  **(3 marks)** Use standard results to obtain the first four non-zero terms of the series expansion of

$$sin{(3x^2)}$$

c.  **(4 marks)** Use standard results to show that for all real values of $x$

$$\cosh^{2}{x \geq 1 + x^{2}}$$

::: {.callout-tip title="Solution" collapse="true" icon="false"}
**a** First we notice that the requested expression has a factor of $e^2$. Because Maclaurin series approximate $e^t$ as a polynomial series, it means that we need to factorise before applying the standard rule for $e^t$. 

Using laws of indices, we get 
$$e^{2-x}=e^2e^{-x}$${#eq-4a}
Now we apply the standard result for $e^t=\sum_{r=0}^\infty\frac{t^r}{r!}$, $\forall t\in \mathbb{R}$ for $t=-x$ to obtain the first four terms of the series expansion for $e^{-x}$.
\begin{equation*}
\begin{split}
e^{-x}&=1+(-x)+\frac{(-x)^2}{2!}+\frac{(-x)^3}{3!} \\
&=1-x+\frac{x^2}{2!}-\frac{x^3}{3!}
\end{split}
\end{equation*}
Thus, from @eq-1a 
$$e^{2-x}=e^2\left(1-x+\frac{x^2}{2!}-\frac{x^3}{3!}\right)$$
**b** We use the standard results $\sin t = \sum_{r=0}^\infty (-1)^r \frac{t^{2r+1}}{(2r+1)!}$, $\forall t \in \mathbb{R}$ for $t=3x^2$, to find the first four non-zero terms.

\begin{equation*}
\begin{split}
\sin 3x^2 &= 3x^2 - \frac{(3x^2)^3}{3!}+ \frac{(3x^2)^5}{5!}-\frac{(3x^2)^7}{7!} \\
&=3x^2 -\frac{3^3}{3!}x^6+\frac{3^5}{5!}x^10-\frac{3^7}{7!}x^14 \\
&=3x^2 -\frac{9}{2}x^6+\frac{81}{40}x^10-\frac{243}{560}x^14
\end{split}
\end{equation*}

**c**  
$$\cosh x = \frac{1}{2}(e^x+e^{-x})$${#eq-4b}
We need to consider the standard result for $e^t$.

\begin{equation*}
\begin{split}
e^{x}&=1+2x+\frac{x^2}{2!}+\frac{x^3}{3!}+\frac{x^4}{4!} \quad ... \\
e^{-x}&=1+(-x)+\frac{(-x)^2}{2!}+\frac{(-x)^3}{3!}+\frac{(x)^4}{4!} \quad ... \\
&=1-x+\frac{(x)^2}{2!}-\frac{(x)^3}{3!}+\frac{(x)^4}{4!} \quad ... \\
\therefore \qquad e^{x}+e^{-x}&=2+2\frac{(x)^2}{2!}+2\frac{(x)^4}{4!}+ \quad ...
\end{split}
\end{equation*}

By substituting this result in @eq-4b, we get

\begin{equation*}
\begin{split}
\cosh x &= \frac{1}{2} \left( 2+2\frac{(x)^2}{2!}+2\frac{(x)^4}{4!}+ \quad ... \right)\\
&= 1+\frac{(x)^2}{2!}+\textcolor{magenta}{\frac{(x)^4}{4!}+ \quad ...}
\end{split}
\end{equation*}
The residual(you don't need to know how it's called)
$$\frac{(x)^4}{4!}+ \quad ... \geq 0, \quad \forall x \in \mathbb{R}$$
as all terms are of even degree with positive coefficients.

Therefore, $$\cosh x \geq1+\frac{x^2}{2}$$
So, 
\begin{equation*}
\begin{split}
\cosh^2 x &\geq \left(1+\frac{x^2}{2}\right)^2 \\
\cosh^2 x &\geq 1+2\frac{x^2}{2}+\frac{x^4}{4} \\
 &\geq 1+x^2
\end{split}
\end{equation*}
as $\frac{x^4}{4}\geq0$, $\forall x \in \mathbb{R}$.

**Alternative method:**
This method is slightly longer but it requires less planning.

First, 
\begin{equation*}
\begin{split}
\cosh^2 x &= \left( \frac{1}{2}(e^x+e^{-x}) \right) ^2 \\
&= \frac{1}{4}(e^x+e^{-x})^2 \\
&= \frac{1}{4}(e^{2x}+2e^x e^{-x}+e^{-2x}) \\
&= \frac{1}{4}(e^{2x}+2+e^{-2x})
\end{split}
\end{equation*}

Thus,
$$\cosh^2x=\frac{1}{2}+\frac{1}{4}(e^{2x}+e^{-2x})$${#eq-4c}

Then we need to consider the standard result for $e^t$. 

[**Note:** to prove the inequality $\forall x \in \mathbb{R}$ using this method, we need to consider the Maclaurin series of $\cosh^2 x$. An approximation is not enough, because we do not know if the approximation underestimates or overestimates the true values.] 

\begin{equation*}
\begin{split}
e^{2x}&=1+2x+\frac{(2x)^2}{2!}+\frac{(2x)^3}{3!}+\frac{(2x)^4}{4!} \quad ... \\
e^{-2x}&=1+(-2x)+\frac{(-2x)^2}{2!}+\frac{(-2x)^3}{3!}+\frac{(2x)^4}{4!} \quad ... \\
&=1-2x+\frac{(2x)^2}{2!}-\frac{(2x)^3}{3!}+\frac{(2x)^4}{4!} \quad ... \\
\therefore \qquad e^{2x}+e^{-2x}&=2+2\frac{(2x)^2}{2!}+2\frac{(2x)^4}{4!}+ \quad ...
\end{split}
\end{equation*}
By substituting this result in @eq-4c, we get
\begin{equation*}
\begin{split}
\cosh ^2 x &=\frac{1}{2}+\frac{1}{4} \left(2+2\frac{(2x)^2}{2!}+2\frac{(2x)^4}{4!}+ \quad ... \right)\\
&=\frac{1}{2}+\frac{1}{2}+\frac{1}{2}\frac{(2x)^2}{2!}+\frac{1}{2}\frac{(2x)^4}{4!}+ \quad ... \\
&=1+x^2+\textcolor{magenta}{\frac{2}{3}x^4+ \quad ...}
\end{split}
\end{equation*}

The residual(you don't need to know how it's called)
$$\frac{2}{3}x^4+ \quad ... \geq 0, \quad \forall x \in \mathbb{R}$$
as all terms are of even degree with positive coefficients.

Therefore, $$\cosh ^2 x \geq 1+x^2$$
:::

## Question 5

a.  **(5 marks**) Show that the series expansion of $ln{\left(\frac{1+3x}{1-2x}\right)}$ in ascending powers of $x$, up to and including the term in $x^4$, is $$\frac{5x^2}{2}+\frac{35x^3}{3}-\frac{65x^4}{4}$$

b.  **(1 mark)** State the range of values of $x$ for which the answer to part **a** is valid.

c.  **(4 marks)** By choosing a suitable value for $x$, use the expansion from part **a** to obtain an estimate for the value of $ln{\frac{1}{2}}$. Give your answer to 3 decimal places.

d.  **(2 marks)** Write down the first four terms of the series expansion for $ln{\sqrt{\frac{1+3x}{1-2x}}}$

::: {.callout-tip title="Solution" collapse="true" icon="false"}
**a** From the laws of logarithms 
$$\ln \left( \frac{1+3x}{1-2x}\right) = \ln (1+3x) + \ln (1 -2x)$${#eq-5a}

From the standard result $\ln(1+t) \sum_{r=0}^{\infty}(-1)^{r+1}\frac{t^r}{r}$, for $-1 < t \leq 1$, for $t=3x$ and $t=-2x$ we've got

\begin{equation*}
\begin{split}
\ln (1+3x) &=3x-\frac{(3x)^2}{2}+\frac{(3x)^3}{3}-\frac{(3x)^4}{4} \\
&= 3x-\frac{9}{2}x^2+9x^3-\frac{81}{4}x^4 \\
\ln (1-2x) &=-2x-\frac{(-2x)^2}{2}+\frac{(-2x)^3}{3}-\frac{(-2x)^4}{4} \\
&=-2x-\frac{(2x)^2}{2}-\frac{(2x)^3}{3}-\frac{(2x)^4}{4} \\
&=-2x-2x^2 -\frac{8}{3}x^3-\frac{16}{4}x^4
\end{split}
\end{equation*}

up to and including $x^4$.

Thus, from @eq-5a
$$\ln \left( \frac{1+3x}{1-2x}\right) \approx 5x-\frac{5}{2}x^2+\frac{35}{3}x^3-\frac{65}{4}x^4$${#eq-5b}

**b** We require the approximation to be valid for both the expansion of $\ln(1+3x)$ and $\ln(1-2x)$. 
Therefore, @eq-5b is valid for $$-\frac{1}{3} < x \leq -\frac{1}{3}$$

**c** First we need to find the value of x that satisfies the equality
\begin{equation*}
\begin{split}
\frac{1+3x}{1-2x}&=\frac{1}{2} \\
2(1+3x) &=1-2x \\
2+6x&=1-2x\\
8x&=-1\\
x&=-\frac{1}{8}
\end{split}
\end{equation*}

By substituting $x=-\frac{1}{8}$ in @eq-5b

\begin{equation*}
\begin{split}
\ln \left( \frac{1}{2} \right)& \approx  5\left(- \frac{1}{8} \right)-\frac{5}{2}\left( -\frac{1}{8} \right)^2+\frac{35}{3}\left(- \frac{1}{8} \right)^3-\frac{65}{4}\left( -\frac{1}{8} \right)^4 \\
&=-0.6908162435 \\
&= 0.691 \quad \textsf{(3 d.p.)}
\end{split}
\end{equation*}

**d** By the laws of logarithms

\begin{equation*}
\begin{split}
\ln \left( \sqrt{\frac{1+3x}{1-2x}}\right)&= \left(\ln \left( \frac{1+3x}{1-2x}\right)\right)^{\frac{1}{2}} \\
&=\frac{1}{2}\ln \left( \sqrt{\frac{1+3x}{1-2x}}\right) \\
& \approx \frac{5}{2}x-\frac{5}{4}x^2+\frac{35}{6}x^3-\frac{65}{8}x^4
\end{split}
\end{equation*}

:::

## Question 6

*(from Q2 Paper 1 November 2021)*

a.  **(2 marks)** Use the Maclaurin series expansion for $\cos x$ to determine the series expansion of $\cos^{2}\frac{x}{3}$ in ascending powers of $x$,up to and including the term $x^{4}$.

    Give each term in simplest form.

b.  **(3 marks)** Use the answer to part *a* and calculus to find an approximation, to 5 decimal places, for

$$\int_{\pi/6}^{\pi/2}{\left( \frac{1}{x}\cos^{2}\left( \frac{x}{3} \right) \right)dx}$$ Given that $\int_{}^{}{\frac{1}{x}dx = \ln{x + c}}$.

::: {.callout-tip title="Solution" collapse="true" icon="false"}
**a** To simplify the calculations, we can consider the double angle formula

$$\cos^2 t = \frac{1}{2}(1+\cos 2t)$$
Using the standard results for the expansion of $\cos t$
\begin{equation*}
\begin{split}
\cos^2 t &= \frac{1}{2}(1+1-\frac{(2t)^2}{2!}+\frac{(2t)^4}{4!}\quad ...) \\
&=1-t^2+\frac{1}{3}t^4\quad ...
\end{split}
\end{equation*}

By substituting $t=\frac{x}{3}$, we get
\begin{equation*}
\begin{split}
\cos^2 \left(\frac{x}{3}\right) &= 1-\left(\frac{x}{3}\right)^2+\frac{1}{3}\left(\frac{x}{3}\right)^4 \\
&=1-\frac{x^2}{9}+\frac{x^4}{243}
\end{split}
\end{equation*}
up to and including $x^4$.

**b** From part a

\begin{equation*}
\begin{split}
\int_{\frac{\pi}{6}}^{\frac{\pi}{2}} \frac{1}{x} \cos ^2\left(\frac{x}{3}\right) \,dx &= \int_{\frac{\pi}{6}}^{\frac{\pi}{2}} \frac{1}{x} \left(1-\frac{x^2}{9}+\frac{x^4}{243}\right) \,dx \\
&= \int_{\frac{\pi}{6}}^{\frac{\pi}{2}} \frac{1}{x} -\frac{x}{9}+\frac{x^3}{243} \,dx \\
&=\left[ \ln x - \frac{x^2}{18} + \frac{x^4}{972}\right]_{\frac{\pi}{6}}^{\frac{\pi}{2}} \\
&= 0.98295 
\end{split}
\end{equation*}
:::
